# Generated by Django 2.2.5 on 2019-10-11 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('viewable', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('postgraduate', models.BooleanField(default=False)),
                ('submissionDate', models.DateField(blank=True, null=True)),
                ('supervisor2Title', models.CharField(blank=True, max_length=20)),
                ('supervisor2FirstName', models.CharField(blank=True, max_length=30)),
                ('supervisor2LastName', models.CharField(blank=True, max_length=30)),
                ('supervisor3Title', models.CharField(blank=True, max_length=20)),
                ('supervisor3FirstName', models.CharField(blank=True, max_length=30)),
                ('supervisor3LastName', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('noOfStudents', models.IntegerField()),
                ('prerequisites', models.CharField(max_length=1000)),
                ('projectTags', models.CharField(max_length=1000)),
                ('IP', models.CharField(max_length=22)),
                ('chemical', models.BooleanField(default=False)),
                ('civil', models.BooleanField(default=False)),
                ('elec', models.BooleanField(default=False)),
                ('envir', models.BooleanField(default=False)),
                ('materials', models.BooleanField(default=False)),
                ('mechanical', models.BooleanField(default=False)),
                ('mechatronic', models.BooleanField(default=False)),
                ('mining', models.BooleanField(default=False)),
                ('oilGas', models.BooleanField(default=False)),
                ('petroleum', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('supervisor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('unitID', models.AutoField(primary_key=True, serialize=False)),
                ('unitCode', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UnitProjectLink',
            fields=[
                ('linkID', models.AutoField(primary_key=True, serialize=False)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.ProjectModel')),
                ('unitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.UnitModel')),
            ],
            options={
                'unique_together': {('projectID', 'unitID')},
            },
        ),
    ]
