# Generated by Django 2.2.4 on 2019-09-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=50)),
                ('companyDescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('noOfStudents', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('confirmed', models.BooleanField(default=False)),
                ('viewable', models.BooleanField(default=False)),
                ('creationDate', models.DateField()),
                ('deadlineDate', models.DateField()),
                ('chemical', models.BooleanField(default=False)),
                ('civil', models.BooleanField(default=False)),
                ('elec', models.BooleanField(default=False)),
                ('envir', models.BooleanField(default=False)),
                ('materials', models.BooleanField(default=False)),
                ('mechanical', models.BooleanField(default=False)),
                ('mechatronic', models.BooleanField(default=False)),
                ('mining', models.BooleanField(default=False)),
                ('oilGas', models.BooleanField(default=False)),
                ('petroleum', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisorID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('projectClientID', models.IntegerField(primary_key=True, serialize=False)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.Client')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.Project')),
            ],
        ),
    ]
