# Generated by Django 2.2.5 on 2019-09-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProposalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('projectID', models.IntegerField(primary_key=True, serialize=False)),
                ('supervisor2Title', models.CharField(max_length=20)),
                ('supervisor2FirstName', models.CharField(max_length=30)),
                ('supervisor2LastName', models.CharField(max_length=30)),
                ('supervisor3Title', models.CharField(max_length=20)),
                ('supervisor3FirstName', models.CharField(max_length=30)),
                ('supervisor3LastName', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('noOfStudents', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('viewable', models.BooleanField(default=False)),
                ('prerequisites', models.CharField(max_length=1000)),
                ('projectTags', models.CharField(max_length=1000)),
                ('IP', models.CharField(max_length=22)),
                ('chemical', models.BooleanField(default=False)),
                ('civil', models.BooleanField(default=False)),
                ('elec', models.BooleanField(default=False)),
                ('envir', models.BooleanField(default=False)),
                ('materials', models.BooleanField(default=False)),
                ('mechanical', models.BooleanField(default=False)),
                ('mechatronic', models.BooleanField(default=False)),
                ('mining', models.BooleanField(default=False)),
                ('oilGas', models.BooleanField(default=False)),
                ('petroleum', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('draft', models.BooleanField()),
                ('postgraduate', models.BooleanField()),
                ('creationDate', models.DateField()),
                ('deadlineDate', models.DateField()),
                ('Supervisor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='projectclient',
            name='clientID',
        ),
        migrations.RemoveField(
            model_name='projectclient',
            name='projectID',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectClient',
        ),
    ]
