# Generated by Django 2.2.5 on 2019-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0002_auto_20190908_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='Supervisor1',
            new_name='supervisor1',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
