# Generated by Django 2.2.5 on 2019-10-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0002_auto_20191012_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unitmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='onCampus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='unitCode',
            field=models.CharField(max_length=32),
        ),
    ]
