# Generated by Django 2.2.5 on 2019-10-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0002_auto_20191001_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unitprojectlink',
            unique_together={('projectID', 'unitID')},
        ),
    ]
