# Generated by Django 2.2.5 on 2019-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0003_auto_20191014_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='prerequisites',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectTags',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
