# Generated by Django 2.2.5 on 2019-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0003_auto_20190908_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='creationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='deadlineDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='postgraduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
