# Generated by Django 2.2.5 on 2019-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0004_auto_20190909_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor2FirstName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor2LastName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor2Title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor3FirstName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor3LastName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor3Title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
