# Generated by Django 2.2.5 on 2019-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0005_auto_20190911_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor2FirstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor2LastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor2Title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor3FirstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor3LastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='supervisor3Title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
