# Generated by Django 2.2.5 on 2019-09-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0006_auto_20190911_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='deadlineDate',
            field=models.DateField(blank=True),
        ),
    ]
