# Generated by Django 2.2.5 on 2019-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0009_auto_20190923_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('unitID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fieldOfDiscipline', models.CharField(blank=True, max_length=200)),
                ('coordinatorName', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('prerequisites', models.TextField(blank=True)),
                ('contentInfo', models.CharField(blank=True, max_length=256)),
                ('outcomes', models.CharField(blank=True, max_length=256)),
                ('assessmentInfo', models.CharField(blank=True, max_length=256)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
