# Generated by Django 2.2.5 on 2019-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0011_auto_20190926_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='unitCode',
            field=models.CharField(default='Error', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='unitID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
