# Generated by Django 2.2.5 on 2019-09-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0014_auto_20190926_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.CreateModel(
            name='UnitProjectLink',
            fields=[
                ('linkID', models.AutoField(primary_key=True, serialize=False)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.ProjectModel')),
                ('unitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProposalApp.UnitModel')),
            ],
        ),
    ]
