# Generated by Django 2.2.5 on 2019-09-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProposalApp', '0015_auto_20190926_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='deadlineDate',
        ),
    ]
