from django import forms

NUMBER_OF_STUDENTS =[(1,1), (2,2), (3,3), (4,4), (5,5), (6,6)]
IP_OPTIONS = [("Sponsor will retain IP", "Sponsor will retain IP"), ("UWA will retain IP", "UWA will retain IP")]

class ProjectProposalForm(forms.Form):
    title = forms.CharField(label = 'Title')
    description = forms.CharField(label = 'Description')
    noOfStudents = forms.IntegerField(label = 'Number of students', widget = forms.Select(choices=NUMBER_OF_STUDENTS))
    projectTags = forms.CharField(label = 'Project Tags')
    prerequisites = forms.CharField(label = 'Prerequisites')
    IP = forms.CharField(label = 'IP',  widget = forms.Select(choices=IP_OPTIONS))
    chemical = forms.BooleanField(label = 'Chemical')
    civil = forms.BooleanField(label = 'Civil')
    elec = forms.BooleanField(label = 'Electrical')
    envir = forms.BooleanField(label = 'Environmental')
    materials = forms.BooleanField(label = 'Materials')
    mechanical = forms.BooleanField(label = 'Mechanical')
    mechatronic = forms.BooleanField(label = 'Mechatronic')
    mining = forms.BooleanField(label = 'Mining')
    oilGas = forms.BooleanField(label = 'Oil and Gas')
    petroleum = forms.BooleanField(label = 'Petroleum')
    software = forms.BooleanField(label = 'Software')
    other = forms.BooleanField(label = 'Other')

"""chemical = forms.BooleanField(label = 'chemical')
civil = forms.BooleanField()
elec = forms.BooleanField()
envir = forms.BooleanField()
materials = forms.BooleanField()
mechanical = forms.BooleanField()
mechatronic = forms.BooleanField()
mining = forms.BooleanField()
oilGas = forms.BooleanField()
petroleum = forms.BooleanField()
software = forms.BooleanField()
other = forms.BooleanField()
timeRequired = forms.CharField(max_length = 1000)
confirmed = forms.BooleanField(default=False)
viewable = forms.BooleanField(default=False)
creationDate = forms.DateField()
deadlineDate = forms.DateField()

#checkboxes
chemical = forms.BooleanField(default=False)
civil = forms.BooleanField(default=False)
elec = forms.BooleanField(default=False)
envir = forms.BooleanField(default=False)
materials = forms.BooleanField(default=False)
mechanical = forms.BooleanField(default=False)
mechatronic = forms.BooleanField(default=False)
mining = forms.BooleanField(default=False)
oilGas = forms.BooleanField(default=False)
petroleum = forms.BooleanField(default=False)
software = forms.BooleanField(default=False)
other = forms.BooleanField(default=False)"""
