# Generated by Django 2.2.5 on 2019-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=120)),
                ('Phone', models.IntegerField()),
                ('Company_Name', models.CharField(max_length=100)),
                ('Company_Business', models.CharField(max_length=100)),
            ],
        ),
    ]
