# Generated by Django 2.2.5 on 2019-10-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Organisation_Business',
            new_name='Organisation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Organisation_Name',
        ),
    ]
