# Generated by Django 2.2.5 on 2019-10-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190911_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Company_Business',
            new_name='Organisation_Business',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Company_Name',
            new_name='Organisation_Name',
        ),
    ]
